#!/bin/bash
# Script to capture colorful rssm demo output

echo "📸 Capturing rssm Demo with colors..."
echo ""
echo "Option 1: Using script command (macOS/Linux)"
echo "script -q /dev/null docker run -t rssm-demo | tee rssm-demo.log"
echo ""
echo "Option 2: Using asciinema (install with: brew install asciinema)"
echo "asciinema rec -c 'docker run -t rssm-demo' rssm-demo.cast"
echo "asciinema play rssm-demo.cast"
echo ""
echo "Option 3: Convert to GIF using svg-term-cli"
echo "npm install -g svg-term-cli"
echo "docker run -t rssm-demo | svg-term --out rssm-demo.svg"
echo ""
echo "Option 4: Manual screenshot"
echo "1. Run: docker run -t rssm-demo"
echo "2. Take a screenshot of your terminal"
echo ""
echo "The demo features:"
echo "🌈 Rainbow gradient ASCII art logo"
echo "💚 Green success messages"
echo "💙 Cyan commands and paths"
echo "💛 Yellow headers"
echo "💜 Purple bordered tip boxes"
echo "❤️  Red syntax highlighting"